// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worktree$0 from "../worktree/models.js";

export function ChooseProjectDirectory(): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(2530598594).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ChooseTerminalExecutable(): $CancellablePromise<string> {
    return $Call.ByID(2945861578);
}

export function ClearSessions(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(1581048421).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CloseSession(id: string): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(773215935, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CloseSettingsWindow(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(2709661388).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateHarness(next: domain$0.Harness): $CancellablePromise<domain$0.Harness> {
    return $Call.ByID(1928421377, next).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateWorktree(req: worktree$0.CreateRequest): $CancellablePromise<domain$0.Worktree> {
    return $Call.ByID(1479407878, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FocusSession(id: string): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(2280795835, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetBootstrap(): $CancellablePromise<domain$0.Bootstrap> {
    return $Call.ByID(96701757).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetInitialSettingsSection(): $CancellablePromise<string> {
    return $Call.ByID(565034941);
}

export function GetPreferences(): $CancellablePromise<domain$0.Preferences> {
    return $Call.ByID(409643873).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetWindowRole(): $CancellablePromise<string> {
    return $Call.ByID(2012294445);
}

export function HideWindow(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(197083831).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LaunchSession(req: session$0.LaunchRequest): $CancellablePromise<domain$0.Session> {
    return $Call.ByID(1182409108, req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListHarnesses(): $CancellablePromise<domain$0.Harness[]> {
    return $Call.ByID(3733684909).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListProjects(): $CancellablePromise<domain$0.Project[]> {
    return $Call.ByID(2940915421).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListSessions(): $CancellablePromise<domain$0.Session[]> {
    return $Call.ByID(4136909550).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListTerminalAdapters(): $CancellablePromise<domain$0.TerminalAdapter[]> {
    return $Call.ByID(1764859963).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListTerminalProfiles(): $CancellablePromise<domain$0.TerminalProfile[]> {
    return $Call.ByID(960278845).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListWorktreeBranches(projectID: string): $CancellablePromise<string[]> {
    return $Call.ByID(800837838, projectID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListWorktrees(projectID: string): $CancellablePromise<domain$0.Worktree[]> {
    return $Call.ByID(2638225679, projectID).then(($result: any) => {
        return $$createType15($result);
    });
}

export function OpenSettingsDialog(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(3196645606).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenSettingsSection(section: string): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(258372105, section).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Quit(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(310506672).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveHarness(id: string): $CancellablePromise<void> {
    return $Call.ByID(2333281573, id);
}

export function RemoveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1823611048, id);
}

export function RemoveTerminalProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3220119688, id);
}

export function RemoveWorktree(projectID: string, path: string, force: boolean): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(1103833882, projectID, path, force).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReorderHarnesses(ids: string[]): $CancellablePromise<domain$0.Harness[]> {
    return $Call.ByID(3075841878, ids).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ReorderProjects(ids: string[]): $CancellablePromise<domain$0.Project[]> {
    return $Call.ByID(1026356684, ids).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ReorderTerminalAdapters(ids: string[]): $CancellablePromise<domain$0.TerminalAdapter[]> {
    return $Call.ByID(419985346, ids).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ResetSidebarWindow(): $CancellablePromise<domain$0.WindowState> {
    return $Call.ByID(4245109158).then(($result: any) => {
        return $$createType16($result);
    });
}

export function RunAction(action: string): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(1521377898, action).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SelectProject(id: string): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(2002296164, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetDefaultProject(id: string): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(3861287575, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ShowWindow(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(1953061286).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ToggleAlwaysOnTop(): $CancellablePromise<domain$0.WindowState> {
    return $Call.ByID(2286002874).then(($result: any) => {
        return $$createType16($result);
    });
}

export function UpdateHarness(next: domain$0.Harness): $CancellablePromise<domain$0.Harness> {
    return $Call.ByID(2011914430, next).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdatePreferences(prefs: domain$0.Preferences): $CancellablePromise<domain$0.Preferences> {
    return $Call.ByID(834007532, prefs).then(($result: any) => {
        return $$createType5($result);
    });
}

export function UpsertTerminalProfile(profile: domain$0.TerminalProfile): $CancellablePromise<domain$0.TerminalProfile> {
    return $Call.ByID(3965059209, profile).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.Project.createFrom;
const $$createType1 = domain$0.ActionResult.createFrom;
const $$createType2 = domain$0.Harness.createFrom;
const $$createType3 = domain$0.Worktree.createFrom;
const $$createType4 = domain$0.Bootstrap.createFrom;
const $$createType5 = domain$0.Preferences.createFrom;
const $$createType6 = domain$0.Session.createFrom;
const $$createType7 = $Create.Array($$createType2);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = $Create.Array($$createType6);
const $$createType10 = domain$0.TerminalAdapter.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = domain$0.TerminalProfile.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = $Create.Array($$createType3);
const $$createType16 = domain$0.WindowState.createFrom;
