// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 聚合桌面窗口、配置、项目、终端和会话服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worktree$0 from "../worktree/models.js";

/**
 * ChooseProjectDirectory 打开目录选择器并添加选中的项目
 */
export function ChooseProjectDirectory(): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(2530598594).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ChooseTerminalExecutable 打开文件选择器并返回终端可执行文件路径
 */
export function ChooseTerminalExecutable(): $CancellablePromise<string> {
    return $Call.ByID(2945861578);
}

/**
 * ClearSessions 清空会话列表，并返回最新会话列表
 */
export function ClearSessions(): $CancellablePromise<domain$0.SessionActionResult> {
    return $Call.ByID(1581048421).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CloseSession 关闭或移除指定会话，并返回最新会话列表
 */
export function CloseSession(id: string): $CancellablePromise<domain$0.SessionActionResult> {
    return $Call.ByID(773215935, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CloseSettingsWindow 关闭设置窗口
 */
export function CloseSettingsWindow(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(2709661388).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CreateHarness 创建助手配置并广播最新列表
 */
export function CreateHarness(next: domain$0.Harness): $CancellablePromise<domain$0.Harness> {
    return $Call.ByID(1928421377, next).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateWorktree 创建新的 Git worktree，并返回最新 worktree 列表
 */
export function CreateWorktree(req: worktree$0.CreateRequest): $CancellablePromise<domain$0.WorktreeActionResult> {
    return $Call.ByID(1479407878, req).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * FocusSession 聚焦指定会话，必要时尝试重新打开终端，并返回最新会话列表
 */
export function FocusSession(id: string): $CancellablePromise<domain$0.SessionActionResult> {
    return $Call.ByID(2280795835, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBootstrap 返回前端启动所需的完整数据
 */
export function GetBootstrap(): $CancellablePromise<domain$0.Bootstrap> {
    return $Call.ByID(96701757).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetInitialSettingsSection 返回设置窗口初始打开的分区
 */
export function GetInitialSettingsSection(): $CancellablePromise<string> {
    return $Call.ByID(565034941);
}

/**
 * GetPreferences 返回当前偏好设置
 */
export function GetPreferences(): $CancellablePromise<domain$0.Preferences> {
    return $Call.ByID(409643873).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetWindowRole 返回当前窗口角色
 */
export function GetWindowRole(): $CancellablePromise<string> {
    return $Call.ByID(2012294445);
}

/**
 * HideWindow 隐藏主窗口
 */
export function HideWindow(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(197083831).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LaunchSession 根据前端传入的请求启动一个新的助手终端会话，并返回最新会话列表
 */
export function LaunchSession(req: session$0.LaunchRequest): $CancellablePromise<domain$0.SessionActionResult> {
    return $Call.ByID(1182409108, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListAllWorktrees 返回所有项目的 Git worktree 列表
 */
export function ListAllWorktrees(): $CancellablePromise<domain$0.Worktree[]> {
    return $Call.ByID(3995349184).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListHarnesses 返回所有助手配置
 */
export function ListHarnesses(): $CancellablePromise<domain$0.Harness[]> {
    return $Call.ByID(3733684909).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListProjects 返回所有项目配置
 */
export function ListProjects(): $CancellablePromise<domain$0.Project[]> {
    return $Call.ByID(2940915421).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSessions 返回带项目展示名的当前会话列表
 */
export function ListSessions(): $CancellablePromise<domain$0.Session[]> {
    return $Call.ByID(4136909550).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListTerminalAdapters 返回当前可展示的终端适配器
 */
export function ListTerminalAdapters(): $CancellablePromise<domain$0.TerminalAdapter[]> {
    return $Call.ByID(1764859963).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ListTerminalProfiles 返回自定义终端配置列表
 */
export function ListTerminalProfiles(): $CancellablePromise<domain$0.TerminalProfile[]> {
    return $Call.ByID(960278845).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ListWorktreeBranches 返回可用于创建 worktree 的分支状态
 */
export function ListWorktreeBranches(projectID: string): $CancellablePromise<domain$0.WorktreeBranchState> {
    return $Call.ByID(800837838, projectID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ListWorktrees 返回项目的 Git worktree 列表
 */
export function ListWorktrees(projectID: string): $CancellablePromise<domain$0.Worktree[]> {
    return $Call.ByID(2638225679, projectID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * OpenSettingsDialog 打开设置窗口
 */
export function OpenSettingsDialog(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(3196645606).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenSettingsSection 打开设置窗口并定位到指定分区
 */
export function OpenSettingsSection(section: string): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(258372105, section).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Quit 退出桌面应用
 */
export function Quit(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(310506672).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RemoveHarness 删除助手配置并广播最新列表
 */
export function RemoveHarness(id: string): $CancellablePromise<void> {
    return $Call.ByID(2333281573, id);
}

/**
 * RemoveProject 删除项目并刷新前端数据
 */
export function RemoveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1823611048, id);
}

/**
 * RemoveTerminalProfile 删除自定义终端配置
 */
export function RemoveTerminalProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3220119688, id);
}

/**
 * RemoveWorktree 删除指定 Git worktree，并返回最新 worktree 列表
 */
export function RemoveWorktree(projectID: string, path: string, force: boolean): $CancellablePromise<domain$0.WorktreeActionResult> {
    return $Call.ByID(1103833882, projectID, path, force).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ReorderHarnesses 重排助手列表并广播最新顺序
 */
export function ReorderHarnesses(ids: string[]): $CancellablePromise<domain$0.Harness[]> {
    return $Call.ByID(3075841878, ids).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ReorderProjects 重排项目列表并刷新前端数据
 */
export function ReorderProjects(ids: string[]): $CancellablePromise<domain$0.Project[]> {
    return $Call.ByID(1026356684, ids).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ReorderTerminalAdapters 保存终端展示顺序
 */
export function ReorderTerminalAdapters(ids: string[]): $CancellablePromise<domain$0.TerminalAdapter[]> {
    return $Call.ByID(419985346, ids).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ResetSidebarWindow 重置侧边栏窗口尺寸和位置
 */
export function ResetSidebarWindow(): $CancellablePromise<domain$0.WindowState> {
    return $Call.ByID(4245109158).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RunAction 执行前端请求的窗口级动作
 */
export function RunAction(action: string): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(1521377898, action).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SelectProject 切换当前项目并刷新前端数据
 */
export function SelectProject(id: string): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(2002296164, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetDefaultProject 设置默认项目并刷新前端数据
 */
export function SetDefaultProject(id: string): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(3861287575, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ShowWindow 显示主窗口并切到前台
 */
export function ShowWindow(): $CancellablePromise<domain$0.ActionResult> {
    return $Call.ByID(1953061286).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ToggleAlwaysOnTop 切换主窗口置顶状态
 */
export function ToggleAlwaysOnTop(): $CancellablePromise<domain$0.WindowState> {
    return $Call.ByID(2286002874).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * UpdateHarness 更新助手配置并广播最新列表
 */
export function UpdateHarness(next: domain$0.Harness): $CancellablePromise<domain$0.Harness> {
    return $Call.ByID(2011914430, next).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdatePreferences 保存用户偏好并刷新相关窗口状态
 */
export function UpdatePreferences(prefs: domain$0.Preferences): $CancellablePromise<domain$0.Preferences> {
    return $Call.ByID(834007532, prefs).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpsertTerminalProfile 创建或更新自定义终端配置
 */
export function UpsertTerminalProfile(profile: domain$0.TerminalProfile): $CancellablePromise<domain$0.TerminalProfile> {
    return $Call.ByID(3965059209, profile).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.Project.createFrom;
const $$createType1 = domain$0.SessionActionResult.createFrom;
const $$createType2 = domain$0.ActionResult.createFrom;
const $$createType3 = domain$0.Harness.createFrom;
const $$createType4 = domain$0.WorktreeActionResult.createFrom;
const $$createType5 = domain$0.Bootstrap.createFrom;
const $$createType6 = domain$0.Preferences.createFrom;
const $$createType7 = domain$0.Worktree.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType3);
const $$createType10 = $Create.Array($$createType0);
const $$createType11 = domain$0.Session.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = domain$0.TerminalAdapter.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = domain$0.TerminalProfile.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = domain$0.WorktreeBranchState.createFrom;
const $$createType18 = domain$0.WindowState.createFrom;
