// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateRequest {
    "projectId": string;
    "projectPath": string;
    "branch": string;
    "baseBranch": string;
    "path": string;
    "baseDir": string;

    /** Creates a new CreateRequest instance. */
    constructor($$source: Partial<CreateRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("baseBranch" in $$source)) {
            this["baseBranch"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("baseDir" in $$source)) {
            this["baseDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateRequest($$parsedSource as Partial<CreateRequest>);
    }
}
