// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ActionResult 表示后端动作执行结果
 */
export class ActionResult {
    "ok": boolean;
    "status": string;
    "message": string;

    /** Creates a new ActionResult instance. */
    constructor($$source: Partial<ActionResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionResult($$parsedSource as Partial<ActionResult>);
    }
}

/**
 * AppSummary 描述应用的基础信息和能力范围
 */
export class AppSummary {
    "name": string;
    "stack": string[];
    "scope": string[];
    "exclusions": string[];

    /** Creates a new AppSummary instance. */
    constructor($$source: Partial<AppSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("stack" in $$source)) {
            this["stack"] = [];
        }
        if (!("scope" in $$source)) {
            this["scope"] = [];
        }
        if (!("exclusions" in $$source)) {
            this["exclusions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSummary {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stack" in $$parsedSource) {
            $$parsedSource["stack"] = $$createField1_0($$parsedSource["stack"]);
        }
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField2_0($$parsedSource["scope"]);
        }
        if ("exclusions" in $$parsedSource) {
            $$parsedSource["exclusions"] = $$createField3_0($$parsedSource["exclusions"]);
        }
        return new AppSummary($$parsedSource as Partial<AppSummary>);
    }
}

/**
 * Bootstrap 表示前端启动时需要的一次性数据
 */
export class Bootstrap {
    "version": string;
    "summary": AppSummary;
    "configPath": string;
    "preferences": Preferences;
    "harnesses": Harness[];
    "projects": Project[];
    "terminalProfiles": TerminalProfile[];
    "adapters": TerminalAdapter[];
    "sessions": Session[];

    /** Creates a new Bootstrap instance. */
    constructor($$source: Partial<Bootstrap> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new AppSummary());
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("preferences" in $$source)) {
            this["preferences"] = (new Preferences());
        }
        if (!("harnesses" in $$source)) {
            this["harnesses"] = [];
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("terminalProfiles" in $$source)) {
            this["terminalProfiles"] = [];
        }
        if (!("adapters" in $$source)) {
            this["adapters"] = [];
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bootstrap instance from a string or object.
     */
    static createFrom($$source: any = {}): Bootstrap {
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField1_0($$parsedSource["summary"]);
        }
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField3_0($$parsedSource["preferences"]);
        }
        if ("harnesses" in $$parsedSource) {
            $$parsedSource["harnesses"] = $$createField4_0($$parsedSource["harnesses"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField5_0($$parsedSource["projects"]);
        }
        if ("terminalProfiles" in $$parsedSource) {
            $$parsedSource["terminalProfiles"] = $$createField6_0($$parsedSource["terminalProfiles"]);
        }
        if ("adapters" in $$parsedSource) {
            $$parsedSource["adapters"] = $$createField7_0($$parsedSource["adapters"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField8_0($$parsedSource["sessions"]);
        }
        return new Bootstrap($$parsedSource as Partial<Bootstrap>);
    }
}

/**
 * Harness 表示一个可启动的 AI 助手配置
 */
export class Harness {
    "id": string;
    "label": string;
    "command": string;
    "enabled": boolean;
    "builtIn": boolean;
    "icon": string;
    "iconSource": string;
    "tint": string;
    "flags": { [_ in string]?: string };
    "flagOptions": HarnessFlag[];

    /** Creates a new Harness instance. */
    constructor($$source: Partial<Harness> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("builtIn" in $$source)) {
            this["builtIn"] = false;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("iconSource" in $$source)) {
            this["iconSource"] = "";
        }
        if (!("tint" in $$source)) {
            this["tint"] = "";
        }
        if (!("flags" in $$source)) {
            this["flags"] = {};
        }
        if (!("flagOptions" in $$source)) {
            this["flagOptions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Harness instance from a string or object.
     */
    static createFrom($$source: any = {}): Harness {
        const $$createField8_0 = $$createType13;
        const $$createField9_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField8_0($$parsedSource["flags"]);
        }
        if ("flagOptions" in $$parsedSource) {
            $$parsedSource["flagOptions"] = $$createField9_0($$parsedSource["flagOptions"]);
        }
        return new Harness($$parsedSource as Partial<Harness>);
    }
}

/**
 * HarnessFlag 表示助手命令支持的可配置参数
 */
export class HarnessFlag {
    "key": string;
    "label": string;
    "type": string;
    "commandFlag": string;
    "default": string;
    "options": string[];

    /** Creates a new HarnessFlag instance. */
    constructor($$source: Partial<HarnessFlag> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("commandFlag" in $$source)) {
            this["commandFlag"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HarnessFlag instance from a string or object.
     */
    static createFrom($$source: any = {}): HarnessFlag {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new HarnessFlag($$parsedSource as Partial<HarnessFlag>);
    }
}

/**
 * Preferences 表示用户偏好设置
 */
export class Preferences {
    "selectedProjectId": string;
    "defaultProjectId": string;
    "language": string;
    "appearance": string;
    "defaultAdapterId": string;
    "terminalCommandTemplate": string;
    "terminalOrder": string[];
    "disabledTerminalIds": string[];
    "harnessOrder": string[];
    "globalShortcut": string;
    "launchInBackground": boolean;
    "worktreeBaseDir": string;
    "worktreeLocation": string;
    "autohideOnBlur": boolean;
    "panelWidth": number;
    "windowWidth": number;
    "windowHeight": number;
    "windowX": number;
    "windowY": number;
    "windowPositionSaved": boolean;
    "alwaysOnTop": boolean;

    /** Creates a new Preferences instance. */
    constructor($$source: Partial<Preferences> = {}) {
        if (!("selectedProjectId" in $$source)) {
            this["selectedProjectId"] = "";
        }
        if (!("defaultProjectId" in $$source)) {
            this["defaultProjectId"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = "";
        }
        if (!("defaultAdapterId" in $$source)) {
            this["defaultAdapterId"] = "";
        }
        if (!("terminalCommandTemplate" in $$source)) {
            this["terminalCommandTemplate"] = "";
        }
        if (!("terminalOrder" in $$source)) {
            this["terminalOrder"] = [];
        }
        if (!("disabledTerminalIds" in $$source)) {
            this["disabledTerminalIds"] = [];
        }
        if (!("harnessOrder" in $$source)) {
            this["harnessOrder"] = [];
        }
        if (!("globalShortcut" in $$source)) {
            this["globalShortcut"] = "";
        }
        if (!("launchInBackground" in $$source)) {
            this["launchInBackground"] = false;
        }
        if (!("worktreeBaseDir" in $$source)) {
            this["worktreeBaseDir"] = "";
        }
        if (!("worktreeLocation" in $$source)) {
            this["worktreeLocation"] = "";
        }
        if (!("autohideOnBlur" in $$source)) {
            this["autohideOnBlur"] = false;
        }
        if (!("panelWidth" in $$source)) {
            this["panelWidth"] = 0;
        }
        if (!("windowWidth" in $$source)) {
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            this["windowHeight"] = 0;
        }
        if (!("windowX" in $$source)) {
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            this["windowY"] = 0;
        }
        if (!("windowPositionSaved" in $$source)) {
            this["windowPositionSaved"] = false;
        }
        if (!("alwaysOnTop" in $$source)) {
            this["alwaysOnTop"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     */
    static createFrom($$source: any = {}): Preferences {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terminalOrder" in $$parsedSource) {
            $$parsedSource["terminalOrder"] = $$createField6_0($$parsedSource["terminalOrder"]);
        }
        if ("disabledTerminalIds" in $$parsedSource) {
            $$parsedSource["disabledTerminalIds"] = $$createField7_0($$parsedSource["disabledTerminalIds"]);
        }
        if ("harnessOrder" in $$parsedSource) {
            $$parsedSource["harnessOrder"] = $$createField8_0($$parsedSource["harnessOrder"]);
        }
        return new Preferences($$parsedSource as Partial<Preferences>);
    }
}

/**
 * Project 表示一个用户项目目录
 */
export class Project {
    "id": string;
    "path": string;
    "label"?: string;
    "isDefault": boolean;
    "lastUsedAt"?: string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * Session 表示一次助手终端会话
 */
export class Session {
    "id": string;
    "harnessId": string;
    "projectId"?: string;
    "adapterId": string;
    "title": string;
    "command": string;
    "workingDir": string;
    "worktreePath"?: string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "pid"?: number;
    "sessionEnv": string;
    "launchMode": string;
    "focusMode": string;
    "closeMode": string;
    "error"?: string;
    "ref": TerminalSessionRef;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("harnessId" in $$source)) {
            this["harnessId"] = "";
        }
        if (!("adapterId" in $$source)) {
            this["adapterId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("sessionEnv" in $$source)) {
            this["sessionEnv"] = "";
        }
        if (!("launchMode" in $$source)) {
            this["launchMode"] = "";
        }
        if (!("focusMode" in $$source)) {
            this["focusMode"] = "";
        }
        if (!("closeMode" in $$source)) {
            this["closeMode"] = "";
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new TerminalSessionRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField17_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField17_0($$parsedSource["ref"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

/**
 * TerminalAdapter 描述一个可用终端适配器
 */
export class TerminalAdapter {
    "id": string;
    "label": string;
    "platform": string;
    "executable"?: string;
    "installed": boolean;
    "enabled": boolean;
    "stability": string;
    "confidence": string;
    "message"?: string;
    "capabilities": TerminalCapability[];

    /** Creates a new TerminalAdapter instance. */
    constructor($$source: Partial<TerminalAdapter> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("stability" in $$source)) {
            this["stability"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalAdapter instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalAdapter {
        const $$createField9_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField9_0($$parsedSource["capabilities"]);
        }
        return new TerminalAdapter($$parsedSource as Partial<TerminalAdapter>);
    }
}

/**
 * TerminalCapability 描述终端适配器的一项能力
 */
export class TerminalCapability {
    "key": string;
    "label": string;
    "supported": boolean;
    "description": string;

    /** Creates a new TerminalCapability instance. */
    constructor($$source: Partial<TerminalCapability> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalCapability {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalCapability($$parsedSource as Partial<TerminalCapability>);
    }
}

/**
 * TerminalProfile 表示用户自定义终端配置
 */
export class TerminalProfile {
    "id": string;
    "label": string;
    "executablePath": string;
    "argumentTemplate": string;
    "workingDirFlag": string;
    "commandMode": string;
    "platform": string;
    "enabled": boolean;

    /** Creates a new TerminalProfile instance. */
    constructor($$source: Partial<TerminalProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("executablePath" in $$source)) {
            this["executablePath"] = "";
        }
        if (!("argumentTemplate" in $$source)) {
            this["argumentTemplate"] = "";
        }
        if (!("workingDirFlag" in $$source)) {
            this["workingDirFlag"] = "";
        }
        if (!("commandMode" in $$source)) {
            this["commandMode"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalProfile($$parsedSource as Partial<TerminalProfile>);
    }
}

/**
 * TerminalSessionRef 保存终端会话的可追踪引用信息
 */
export class TerminalSessionRef {
    "adapterId": string;
    "platform": string;
    "pid"?: number;
    "processTreePids"?: number[];
    "windowId"?: string;
    "tabId"?: string;
    "terminalId"?: string;
    "title": string;
    "cwd": string;
    "identityStrategy": string;
    "capabilitiesSnapshot": string[];
    "canFocus": boolean;
    "canClose": boolean;
    "requiresPlatformGrant": boolean;

    /** Creates a new TerminalSessionRef instance. */
    constructor($$source: Partial<TerminalSessionRef> = {}) {
        if (!("adapterId" in $$source)) {
            this["adapterId"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("identityStrategy" in $$source)) {
            this["identityStrategy"] = "";
        }
        if (!("capabilitiesSnapshot" in $$source)) {
            this["capabilitiesSnapshot"] = [];
        }
        if (!("canFocus" in $$source)) {
            this["canFocus"] = false;
        }
        if (!("canClose" in $$source)) {
            this["canClose"] = false;
        }
        if (!("requiresPlatformGrant" in $$source)) {
            this["requiresPlatformGrant"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSessionRef instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalSessionRef {
        const $$createField3_0 = $$createType19;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("processTreePids" in $$parsedSource) {
            $$parsedSource["processTreePids"] = $$createField3_0($$parsedSource["processTreePids"]);
        }
        if ("capabilitiesSnapshot" in $$parsedSource) {
            $$parsedSource["capabilitiesSnapshot"] = $$createField10_0($$parsedSource["capabilitiesSnapshot"]);
        }
        return new TerminalSessionRef($$parsedSource as Partial<TerminalSessionRef>);
    }
}

/**
 * WindowState 表示桌面窗口状态
 */
export class WindowState {
    "width": number;
    "height": number;
    "alwaysOnTop": boolean;
    "mode": string;

    /** Creates a new WindowState instance. */
    constructor($$source: Partial<WindowState> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("alwaysOnTop" in $$source)) {
            this["alwaysOnTop"] = false;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState($$parsedSource as Partial<WindowState>);
    }
}

/**
 * Worktree 表示一个 Git worktree
 */
export class Worktree {
    "id": string;
    "projectId": string;
    "path": string;
    "branch": string;
    "baseBranch"?: string;
    "head"?: string;
    "isMain": boolean;
    "dirty": boolean;
    "exists": boolean;
    "status": string;
    "createdAt"?: string;

    /** Creates a new Worktree instance. */
    constructor($$source: Partial<Worktree> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("isMain" in $$source)) {
            this["isMain"] = false;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Worktree instance from a string or object.
     */
    static createFrom($$source: any = {}): Worktree {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Worktree($$parsedSource as Partial<Worktree>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AppSummary.createFrom;
const $$createType2 = Preferences.createFrom;
const $$createType3 = Harness.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Project.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = TerminalProfile.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = TerminalAdapter.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Session.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = HarnessFlag.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = TerminalSessionRef.createFrom;
const $$createType17 = TerminalCapability.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($Create.Any);
