// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LaunchRequest {
    "harnessId": string;
    "projectId": string;
    "adapterId": string;
    "command": string;
    "workingDir": string;
    "title": string;
    "flagOverrides": { [_ in string]?: string };
    "worktreePath": string;

    /** Creates a new LaunchRequest instance. */
    constructor($$source: Partial<LaunchRequest> = {}) {
        if (!("harnessId" in $$source)) {
            this["harnessId"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("adapterId" in $$source)) {
            this["adapterId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("flagOverrides" in $$source)) {
            this["flagOverrides"] = {};
        }
        if (!("worktreePath" in $$source)) {
            this["worktreePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchRequest {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flagOverrides" in $$parsedSource) {
            $$parsedSource["flagOverrides"] = $$createField6_0($$parsedSource["flagOverrides"]);
        }
        return new LaunchRequest($$parsedSource as Partial<LaunchRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
